#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Project Euler Problem 44
=======================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?

"""


def main():
    pentagonals = []
    lowest_diff = float("inf")
    for n in range(1, 50001):
        pentagonal = int(n * (3 * n - 1) / 2)
        pentagonals.append(pentagonal)

    pents = set(pentagonals)

    for i in range(1, 30000):
        pentagonal = pentagonals[i]
        last_diff = pentagonal - pentagonals[i - 1]
        if last_diff > lowest_diff:
            print("lowest diff possible: ", lowest_diff)
            return

        # print pentagonal, [p for p in reversed(pentagonals[:i])]
        for other_pentagonal in reversed(pentagonals[:i]):
            diff = pentagonal - other_pentagonal
            if diff > lowest_diff:
                break

            summ = pentagonal + other_pentagonal
            if diff in pents and summ in pents:
                lowest_diff = diff

            if summ > pentagonals[-1]:
                print("need more")
                return

    return lowest_diff


if __name__ == "__main__":
    import ntpath
    import time
    from common.shared_functions import verify_solution

    problem_number = int(ntpath.basename(__file__).replace("euler", "").replace(".py", ""))
    print("Retrieving my answer to Euler Problem {0} ...".format(problem_number))

    ts = time.time()
    my_answer = main()
    te = time.time()

    print("My answer: {1}".format(problem_number, my_answer))

    verification_type = verify_solution(problem_number, my_answer)
    print("Verification: {0}".format(verification_type.name))
    print("Took {0} seconds.".format(te - ts))
