'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

THRESHOLD = 4000000

def sum_even_fib_terms():
	total = 0

	mem = {}
	mem[0] = 1
	mem[1] = 2

	index = 2
	term = 2

	while term < THRESHOLD:
		if term % 2 == 0:
			total += term

		term = mem[index-1] + mem[index-2]
		mem[index] = term
		index += 1

	return total

print sum_even_fib_terms()


