#!/usr/bin/env python
# -*- coding: utf-8 -*- 
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

pents = set()
hexas = set()


def main():
    for n in xrange(1, 100000):
        tri = n * (n + 1) / 2
        pent = n * (3 * n - 1) / 2
        hexa = n * (2 * n - 1)

        pents.add(pent)
        hexas.add(hexa)

        if tri in pents and tri in hexas:
            if tri > 40755:
                return tri


if __name__ == "__main__": print main()
